spring:
  profiles:
    active: @profile.active@
# todo H2 support
#    active: @profile.active@,@database.profile.active@
  application:
    name: dennis-tool-collection
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 3600
    lettuce:
      pool:
        max-active: 8
        max-wait: 30000
        max-idle: 8
        min-idle: 1
      shutdown-timeout: 10000